version: '3'

services:
  api:
    build: ./cbr_api
    container_name: cbr-api
    command: python3 cbr-api/main.py
    restart: unless-stopped
    environment:
      - LOGS_PATH=/app/logs
      - MODELS_PATH=/app/cbr-api/ml_models
      - DATA_PATH=/app/data
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - models_data:/app/cbr-api/ml_models
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://api:8000"]
    networks:
      - cbr-network

  ui:
    build: ./cbr_ui
    container_name: cbr-ui
    command: >
      streamlit run cbr-ui/main.py
      --server.port=8000
      --logger.level=debug
      --server.fileWatcherType=none
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://ui:8000/_stcore/health"]
    depends_on:
      - api
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://api:8000
    networks:
      - cbr-network

networks:
  cbr-network:
    driver: bridge

volumes:
  models_data:
